Task: Re-activating 11.x-dev tests
pimcore/advanced-object-search pull request #190
Opened 2022-11-11 12:20 UTC by kingjia90

2022-11-14 10:05 UTC, fashxp requested changes, later dismissed

2022-11-14 10:05 UTC, fashxp commented on .github/workflows/static-analysis.yml
> +                    - { php-version: "8.1", dependencies: "highest", pimcore_version: "11.x-dev", phpstan_args: "", experimental: true }
will require some changes further down too ... 
```
composer require --no-update pimcore/pimcore:"${PIMCORE_VERSION} as 10.99.9"
```
--> should say `11.99.9` I guess

2022-11-25 16:15 UTC, dvesh3 commented
Requires #176 for 11.x-dev tests to pass.

2022-11-28 08:03 UTC, fashxp commented
@dvesh3 we could already change dependency from `ongr/elasticsearch-dsl` to `handcraftedinthealps/elasticsearch-dsl` ... then it should work also with lower versions of `elasticsearch-dsl` and symfony 6.

2022-11-28 08:10 UTC, dvesh3 commented on composer.json
>      "ongr/elasticsearch-dsl": "^7.0",
```suggestion
    "handcraftedinthealps/elasticsearch-dsl": "^7.0",
```

2022-11-30 07:51 UTC, dvesh3 commented on composer.json
> +    "pimcore/pimcore": "^10.5 || ^11",
```suggestion
    "pimcore/pimcore": "^10.6 || ^11.0",
```

2022-11-30 09:04 UTC, merged